"""empty message

Revision ID: 263e57a71dd6
Revises: 5d780272df1d
Create Date: 2022-12-11 01:47:29.907560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263e57a71dd6'
down_revision = '5d780272df1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album_and_song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('album_and_song')
    # ### end Alembic commands ###
