"""empty message

Revision ID: b2ef0bf5952f
Revises: e310e2896199
Create Date: 2022-12-13 18:58:43.391935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2ef0bf5952f'
down_revision = 'e310e2896199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.alter_column('albumname',
               existing_type=sa.VARCHAR(length=25, collation='Ukrainian_CI_AS'),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.alter_column('img',
               existing_type=sa.VARCHAR(length=20, collation='Ukrainian_CI_AS'),
               type_=sa.String(length=40),
               existing_nullable=False)

    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.alter_column('song_name',
               existing_type=sa.VARCHAR(length=25, collation='Ukrainian_CI_AS'),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.alter_column('audio',
               existing_type=sa.VARCHAR(length=20, collation='Ukrainian_CI_AS'),
               type_=sa.String(length=40),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.alter_column('audio',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=20, collation='Ukrainian_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('song_name',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=25, collation='Ukrainian_CI_AS'),
               existing_nullable=False)

    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=20, collation='Ukrainian_CI_AS'),
               existing_nullable=False)
        batch_op.alter_column('albumname',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=25, collation='Ukrainian_CI_AS'),
               existing_nullable=False)

    # ### end Alembic commands ###
