"""empty message

Revision ID: e310e2896199
Revises: 263e57a71dd6
Create Date: 2022-12-13 18:23:00.350843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e310e2896199'
down_revision = '263e57a71dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500, collation='Ukrainian_CI_AS'),
               type_=sa.String(length='max'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length='max'),
               type_=sa.VARCHAR(length=500, collation='Ukrainian_CI_AS'),
               existing_nullable=False)

    # ### end Alembic commands ###
